#!/bin/bash
# Run this script to check segmentation in MRIcron on all subjects within a user-defined directory.
# Script goes through all folders (assuming subject folders with anatomical images inside) loading the specified image wildcard and the three segmented images (c1, c2, c3) as overlays. Once you close MRIcron, it will open the next subject.

loc=$(zenity --file-selection --directory --title "Select Structural Directory")

for subj in `ls ${loc}`
  do
    find ${loc}/${subj} -name WOODWARD*.nii -printf "%f\n"
    mricron ${loc}/${subj}/WOODWARD*.nii -o ${loc}/${subj}/c1WOODWARD*.nii -o ${loc}/${subj}/c2WOODWARD*.nii -o ${loc}/${subj}/c3WOODWARD*.nii -x
done
